codestates-seb/seb45_main_011

client/next.config.js

* 배포 관련 환경 설정을 진행합니다.
* 작업 내용
---
Close #16

[FE] 🚀 배포 관련 환경 설정

---

client/src/components/common/Logo.tsx

* Logo component를 구현했습니다.
* size를 props로 받아 size type별로 컴포넌트를 구현했습니다.
* 우선 반응형으로 생각하여 스타일링 했는데 반응형이 좋을지 고정값이 좋을지 논의해봐도 좋을것 같습니다.
---
Close #20

[FE]  ✨ Logo 컴포넌트 구현

---

client/package-lock.json
client/src/components/common/Header/Header.tsx
client/src/components/common/Header/HeaderLink.tsx
client/src/constants/contents.ts

* Header와 HeaderLink 컴포넌트를 리팩토링 했습니다.
* 기존에 작성했던 Header 컴포넌트에서 props로 받아와 HeaderLink 컴포넌트를 props에 따라 렌더링하게 구현했습니다.
* 추후 constant 폴더에 사용할 url 객체를 만든다면 location을 수정하도록 하겠습니다.
* 로그아웃 버튼은 어떤식으로 보여지게 할지 논의해봐야 할 것 같습니다.
---
Close #49 #50

[FE] ♻️ Header 컴포넌트 리팩토링

---

client/src/components/common/Intro.tsx
client/src/constants/contents.ts
client/src/styles/globals.css

* Intro 컴포넌트를 리팩토링 했습니다.
*  정적 text 따로 분리
* 배경 이미지 수정
---
Close #51

[FE] ♻️ Intro 컴포넌트 리팩토링

---

client/src/app/layout.tsx
client/src/components/common/Logo.tsx

* Logo 컴포넌트를 리팩토링 했습니다.
* LPC 이미지 최적화 (로고 priority 속성 추가)
* props type 수정
* 초기 width, height 수정 (이미지 ratio 유지)
---
Close #52

[FE] ♻️ Logo 컴포넌트 리팩토링

---

client/src/components/common/Logo.tsx

* Logo 컴포넌트를 Link 태크고 변경하였습니다.
* Logo 컴포넌트 클릭 시 홈 ('/')으로 리다이렉트 됩니다.

[FE] 🐛 Logo 컴포넌트 라우팅 추가

---

client/src/components/Plant.tsx
client/src/components/PlantCard.tsx
client/src/components/common/CommonButton.tsx
client/src/constants/contents.ts
client/src/styles/globals.css
client/src/types/common.d.ts

* PlantCard 컴포넌트를 구현합니다.
* 작업 내용
* 구현 이미지
---
Close #42

[FE] ✨ PlantCard 컴포넌트 구현

---

.gitignore

gitignore 수정
gitignore 수정
gitignore 수정
---

[BE] ✏️ Chore : gitignore 수정

---

client/src/app/signin/page.tsx
client/src/app/signup/page.tsx
client/src/components/common/Header/Header.tsx
client/src/components/common/Header/HeaderLink.tsx
client/src/components/common/SignInput.tsx
client/src/components/sign/signin/SigninForm.tsx
client/src/components/sign/signin/SigninTextBox.tsx
client/src/components/sign/signup/SignupForm.tsx
client/src/components/sign/signup/SignupTextBox.tsx
client/src/constants/contents.ts

* SigninInput, SigninForm 컴포넌트를 구현했습니다
* SignupInput, SignupForm 컴포넌트를 구현했습니다
* 구현한 컴포넌트를 같이 PR 보내는게 아닌거 같은데... 자꾸 묶어서 PR 보내게 되네요... 죄송합니다 😭
---
Close #36 #37 #38 

[FE] ✨ SignInput 컴포넌트 구현

---

client/src/components/Diary.tsx
client/src/components/LeafDiary.tsx
client/src/components/LeafInfo.tsx
client/src/components/common/PageTitle.tsx
client/src/mock/leaf.json
client/src/types/common.d.ts

* 제목은 '[FE/BE] ✨ OOO 구현'과 같이 작성합니다.
* LeafInfo 컴포넌트를 구현했습니다.
* 하위 컴포넌트(Diary, LeafDiary, PageTitle)의 스타일 부분을 수정했습니다.
* 경과 일수를 계산하는 함수를 작성했습니다.
* LeafInfo 컴포넌트를 구현했습니다.
---
Close #47

[FE] ✨ LeafInfo 컴포넌트 구현

---

client/src/components/LeafTag.tsx
client/src/styles/globals.css

* LeafTag 컴포넌트를 구현했습니다.
* tailwindCSS로 클래스를 주어 구현할 경우 클래스 이름이 너무 길어져서 utility로 빼서 작업했습니다.
* 화면을 확대할 경우 브라우저의 렌더링 문제로 검은 선이 생기는걸 확인했는데 당장 해결이 어려워 추후 리팩토링이 필요할것 같습니다.
---
Close #76

[FE] ✨ LeafTag 컴포넌트 구현

---

server/src/main/java/com/growstory/domain/account/controller/AccountController.java
server/src/main/java/com/growstory/domain/account/entity/Account.java
server/src/main/java/com/growstory/domain/account/service/AccountService.java
server/src/main/java/com/growstory/domain/leaf/controller/LeafController.java
server/src/main/java/com/growstory/domain/leaf/dto/LeafDto.java
server/src/main/java/com/growstory/domain/leaf/entity/Leaf.java
server/src/main/java/com/growstory/domain/leaf/repository/LeafRepository.java
server/src/main/java/com/growstory/domain/leaf/service/LeafService.java
server/src/main/java/com/growstory/domain/point/entity/Point.java
server/src/main/java/com/growstory/domain/point/service/PointService.java
server/src/main/java/com/growstory/global/auth/handler/OAuth2AccountSuccessHandler.java
server/src/main/java/com/growstory/global/auth/utils/AuthUserUtils.java
server/src/main/java/com/growstory/global/aws/service/S3Uploader.java

[BE] ✨ Feat: leaf 관련 기능 구현
leaf 관련 기능 구현
- 식물카드 등록
- 식물카드 수정
- 식물카드 전체 조회
- 식물카드 단일 조회
- 식물카드 삭제
---
Close #70 

[BE] ✨ Feat: leaf 관련 기능 구현

---

client/src/components/common/ConnectCheckBox.tsx

* ConnectCheckBox 컴포넌트를 구현했습니다.
* assert 폴더의 icon에 check.svg를 추가했습니다!
---
Close #73

[FE]  ✨ ConnectCheckBox 컴포넌트 구현

---

server/src/main/java/com/growstory/domain/leaf/entity/Leaf.java
server/src/main/java/com/growstory/domain/leaf/service/LeafService.java

* 제목은 '[FE/BE] ✨ OOO 구현'과 같이 작성합니다.
* Leaf 엔티티에서 leafNickName 관련 정보 삭제
---
Close #2 

[BE] 🔧 leafNickName 관련 정보 삭제

---

client/package-lock.json
client/package.json
client/src/components/common/HashTag.tsx
client/src/components/common/PasswordInput.tsx
client/src/components/common/TagInputForm.tsx
client/src/components/common/TextArea.tsx
client/src/components/common/TextInput.tsx
client/src/types/common.d.ts

* 각종 Input, TextArea 컴포넌트를 구현했습니다.
* TextInput 컴포넌트 구현 (input text type)
* PasswordInput 컴포넌트 구현 (input password type)
* TagInput 컴포넌트 구현 
---
Close #80

[FE] ✨ Input, TextArea 컴포넌트 구현

---

server/src/main/java/com/growstory/domain/leaf/dto/LeafDto.java
server/src/main/java/com/growstory/domain/leaf/entity/Leaf.java
server/src/main/java/com/growstory/domain/leaf/service/LeafService.java

[BE] ♻️ Refactor : Leaf 관련 코드 리팩토링
Leaf 관련 코드 리팩토링
Leaf 관련 코드 리팩토링
---
Close #1

[BE] ♻️ Refactor : Leaf 관련 코드 리팩토링

---

client/package-lock.json
client/src/app/garden/[id]/page.tsx
client/src/app/layout.tsx
client/src/components/garden/EditModeButton.tsx
client/src/components/garden/EmptyInventoryModal.tsx
client/src/components/garden/GardenMap.tsx
client/src/components/garden/GardenSquares.tsx
client/src/components/garden/LeafExistModal.tsx
client/src/components/garden/PlantCard.tsx
client/src/components/garden/PurchaseInfoModal.tsx
client/src/components/garden/PurchaseModal.tsx
client/src/components/garden/TrackedPlant.tsx
client/src/components/garden/index.ts
client/src/constants/values.ts
client/src/hooks/useEffectOnce.ts
client/src/hooks/useMouseTrack.ts
client/src/hooks/usePlants.ts
client/src/hooks/useRollback.ts
client/src/hooks/useSquares.ts
client/src/stores/gardenModalStore.ts
client/src/stores/gardenStore.ts
client/src/utils/createSquares.ts

* Garden 페이지의 2차 리팩토링을 진행합니다.
* 작업 내용
---
Close #104

[FE/BE] ♻ Garden 페이지 2차 리팩토링

---

server/src/main/java/com/growstory/domain/account/service/AccountService.java
server/src/main/java/com/growstory/domain/point/service/PointService.java
server/src/main/java/com/growstory/global/auth/handler/OAuth2AccountSuccessHandler.java
server/src/main/resources/application-prod.yml

[BE] ♻️ Refactor : Account 관련 기능 리팩토링
Refactor : Account 관련 기능 리팩토링
관리자 계정 추가
관리자 계정 포인트 추가
---
Close #1

[BE] ♻️ Refactor : Account 관련 기능 리팩토링

---

server/src/main/java/com/growstory/domain/images/service/JournalImageService.java

✏️ Chore : JournalImageService.deleteJournalImageWithS3 주석 해제

---

server/src/main/java/com/growstory/domain/leaf/controller/LeafController.java
server/src/main/java/com/growstory/domain/leaf/dto/LeafDto.java
server/src/main/java/com/growstory/domain/leaf/service/LeafService.java
server/src/main/resources/application.yml

[BE] ♻️ Refactor : Leaf 관련 이미지 처리 리팩토링
Leaf 관련 이미지 처리 리팩토링
Leaf 생성 시 이미지 nullable = true 
Leaf 수정 시 이미지 nullable = true
---
Close #1

[BE] ♻️ Refactor : Leaf 관련 이미지 처리 리팩토링

---

server/src/main/java/com/growstory/domain/leaf/entity/Leaf.java
server/src/main/java/com/growstory/domain/leaf/service/LeafService.java
server/src/main/resources/application.yml

* 제목은 '[FE/BE] ✨ OOO 구현'과 같이 작성합니다.
Leaf 이미지 관련 리팩토링
Leaf 이미지 관련 리팩토링
---
Close #1

[BE] ♻️ Refactor : Leaf 이미지 관련 리팩토링

---

server/src/main/java/com/growstory/global/auth/config/SecurityCorsConfig.java

* 제목은 '[FE/BE] ✨ OOO 구현'과 같이 작성합니다.
Account CORS 수정
Account CORS 수정
---
Close #1

[BE] ♻️ Refactor : Account CORS 수정

---

.github/workflows/server.yml
server/src/main/java/com/growstory/domain/journal/controller/JournalController.java
server/src/main/resources/application-prod.yml

* 기타 환경 설정 및 CI/CD 테스트
---
Close #10 

🔧 Conf: prod.yml 환경설정 ddl-auto: create -> update

---

.gitignore
server/src/main/java/com/growstory/domain/journal/controller/JournalController.java
server/src/main/java/com/growstory/global/auth/config/SecurityConfiguration.java

- 식물 일지 전체 조회 요청 데이터 변경
- server.yml 깃 추적관리 대상에서 제외
- 식물 일지 전체 조회 관련 기능 request 파라미터 수정
---
Close #94 

♻️ Refactor: 식물 일지 전체 조회 요청 데이터 변경

---

.github/workflows/server.yml
.gitignore
server/src/main/java/com/growstory/global/auth/config/SecurityConfiguration.java
server/src/main/resources/application-prod.yml

[BE] ✨ Feat : security
[BE] ✨ Feat : security
[BE] ✨ Feat : security
---
Close #1

[BE] ✨ Feat : security

---

server/src/main/java/com/growstory/domain/journal/service/JournalService.java
server/src/main/java/com/growstory/global/advice/GlobalExceptionAdvice.java
server/src/main/java/com/growstory/global/response/ErrorResponder.java

Fix : Journal 목록 식물 관리 카드별 조회.
---
Close #94

🐛 Fix : Journal 목록 식물 관리 카드별 조회

---

server/src/main/java/com/growstory/domain/leaf/entity/Leaf.java
server/src/main/java/com/growstory/domain/leaf/service/LeafService.java
server/src/main/java/com/growstory/global/auth/handler/OAuth2AccountSuccessHandler.java

[BE] ♻️ Refactor : Leaf, Account 관련 기능 리팩토링
[BE] ♻️ Refactor : Leaf, Account 관련 기능 리팩토링
[BE] ♻️ Refactor : Leaf, Account 관련 기능 리팩토링
---
Close #1

[BE] ♻️ Refactor : Leaf, Account 관련 기능 리팩토링

---

server/src/main/java/com/growstory/domain/leaf/entity/Leaf.java
server/src/main/java/com/growstory/domain/leaf/service/LeafService.java
server/src/main/java/com/growstory/global/auth/dto/LoginDto.java
server/src/main/java/com/growstory/global/auth/filter/JwtAuthenticationFilter.java
server/src/main/resources/application-prod.yml

[BE] ♻️ Refactor : Leaf 관련 기능 리팩토링
[BE] ♻️ Refactor : Leaf 관련 기능 리팩토링
Leaf 삭제 시 plantObj 연결 해제
Leaf 삭제 시 journal 삭제
Leaf 삭제 시 journalImage 삭제
---
Close #1

[BE] ♻️ Refactor : Leaf 관련 기능 리팩토링

---

server/src/main/java/com/growstory/domain/comment/entity/Comment.java
server/src/main/java/com/growstory/domain/likes/controller/LikeController.java
server/src/main/java/com/growstory/domain/likes/entity/CommentLike.java
server/src/main/java/com/growstory/domain/likes/service/LikeService.java

[BE] ♻️ Refactor : Like 관련 기능 리팩토링
[BE] ♻️ Refactor : Like 관련 기능 리팩토링
comment like 수정
---
Close #1

[BE] ♻️ Refactor : Like 관련 기능 리팩토링

---

server/build.gradle
server/src/main/java/com/growstory/domain/board/dto/RequestBoardDto.java
server/src/main/java/com/growstory/domain/board/entity/Board.java
server/src/main/java/com/growstory/domain/comment/dto/CommentDto.java
server/src/main/java/com/growstory/domain/comment/entity/Comment.java
server/src/main/java/com/growstory/domain/comment/service/CommentService.java
server/src/main/resources/application.yml
server/src/test/java/com/growstory/domain/comment/controller/CommentControllerTest.java

Comment API Testing
댓글 추가, 수정, 삭제 API 테스팅
build.gradle - dependency에  testImplementation 'org.springframework.security:spring-security-test' 추가
각각 메서드 테스팅 시에도 환경 변수를 설정해줘야 한다. (다른 방법은 없을까?)
access token 처리하는 방법.
---
Close #145 

[BE] 🧪 Comment API Testing

---

server/build.gradle
server/src/main/java/com/growstory/domain/account/dto/AccountDto.java
server/src/test/java/com/growstory/domain/account/controller/AccountControllerTest.java
server/src/test/java/com/growstory/domain/account/service/AccountServiceTest.java

[BE] 🧪 Test : 도경 Comment 관련 기능 테스트, 도형 Account 관련 기능 테스트
[BE] 🧪 Test : 도경 Comment 관련 기능 테스트, 도형 Account 관련 기능 테스트
도경 Comment Controller 테스트
도형 Account Controller 테스트
---
Close #1

[BE] 🧪 Test : 도경 Comment 관련 기능 테스트, 도형 Account 관련 기능 테스트

---

server/src/main/java/com/growstory/domain/account/controller/AccountController.java
server/src/main/java/com/growstory/domain/account/dto/AccountDto.java
server/src/main/java/com/growstory/domain/account/service/AccountService.java

[BE] ✨ Feat : Account 비밀번호 검증 api 추가
Account 비밀번호 검증 api 추가
Account 비밀번호 검증 api 추가
---
Close #1

[BE] ✨ Feat : Account 비밀번호 검증 api 추가

---

.github/workflows/server.yml
server/src/main/java/com/growstory/domain/journal/controller/JournalController.java
server/src/main/resources/application-prod.yml

- Feat: 일지 작성 시 point 갱신 기능 구현
- Refactor: Garden 조회 시 토큰 미검증 리팩토링
- Chore: Commit 내역 재정립
---
Close #19

✨ Feat : 일지 작성시 point 추가 및 Garden 조회 시 토큰 미검증 

---

server/src/main/java/com/growstory/domain/board/dto/RequestBoardDto.java
server/src/main/java/com/growstory/domain/board/entity/Board_HashTag.java
server/src/main/java/com/growstory/domain/board/repository/BoardHashTagResitory.java
server/src/main/java/com/growstory/domain/board/service/BoardService.java
server/src/main/java/com/growstory/domain/hashTag/entity/HashTag.java
server/src/main/java/com/growstory/domain/hashTag/repository/HashTagRepository.java
server/src/main/java/com/growstory/domain/hashTag/service/HashTagService.java

게시판 등록 기능 구현
게시판(해시태그 포함) 등록 기능 구현
---
Close #87 

[BE] ✨게시판 기능 구현

---

server/src/test/java/com/growstory/domain/account/controller/AccountControllerTest.java

[BE] ♻️ Refactor : Account 응답, Leaf 응답 리팩토링
[BE] ♻️ Refactor : Account 응답, Leaf 응답 리팩토링
[BE] ♻️ Refactor : Account 응답, Leaf 응답 리팩토링
---
Close #1

[BE] ♻️ Refactor : Account 응답, Leaf 응답 리팩토링

---

server/src/main/java/com/growstory/domain/account/dto/AccountDto.java
server/src/main/java/com/growstory/domain/account/entity/Account.java
server/src/main/java/com/growstory/domain/account/service/AccountService.java
server/src/main/java/com/growstory/domain/likes/repository/BoardLikeRepository.java
server/src/main/java/com/growstory/domain/likes/repository/CommentLikeRepository.java
server/src/main/java/com/growstory/domain/likes/service/LikeService.java
server/src/test/java/com/growstory/domain/account/controller/AccountControllerTest.java
server/src/test/java/com/growstory/global/customUser/annotation/WithMockCustomUser.java
server/src/test/java/com/growstory/global/customUser/factory/WithMockCustomUserSecurityContextFactory.java

[BE] ♻️ Refactor : Account 응답, Like 리팩토링
Refactor : Account 응답, Like 리팩토링
Account 응답, Like 리팩토링
---
Close #1

[BE] ♻️ Refactor : Account 응답, Like 리팩토링

---

server/build.gradle
server/src/main/java/com/growstory/domain/account/controller/AccountController.java
server/src/main/java/com/growstory/global/config/SwaggerConfig.java
server/src/test/java/com/growstory/domain/account/controller/AccountControllerTest.java

[BE] 🔧 Conf : Swagger Configuration
[BE] 🔧 Conf : Swagger Configuration
[BE] 🔧 Conf : Swagger Configuration
---
Close #1

[BE] 🔧 Conf : Swagger Configuration

---

server/build.gradle

[BE] 🔧 Conf : jacoco Configuration
[BE] 🔧 Conf : jacoco Configuration
---
Close #1

[BE] 🔧 Conf : jacoco Configuration

---

server/src/main/java/com/growstory/domain/account/controller/AccountController.java
server/src/main/java/com/growstory/domain/account/dto/AccountDto.java
server/src/main/java/com/growstory/domain/leaf/controller/LeafController.java
server/src/main/java/com/growstory/domain/leaf/dto/LeafDto.java
server/src/main/java/com/growstory/domain/likes/controller/LikeController.java
server/src/main/java/com/growstory/global/email/controller/EmailController.java
server/src/main/java/com/growstory/global/email/dto/EmailDto.java

[BE] ✏️ Chore : Account, Leaf, Like Swagger 설정
[BE] ✏️ Chore : Account, Leaf, Like Swagger 설정
---
Close #1

[BE] ✏️ Chore : Account, Leaf, Like Swagger 설정

---

server/build.gradle
server/src/main/java/com/growstory/domain/account/controller/AccountController.java
server/src/main/java/com/growstory/domain/account/dto/AccountDto.java
server/src/main/java/com/growstory/domain/account/entity/Account.java
server/src/main/java/com/growstory/domain/account/service/AccountService.java
server/src/main/java/com/growstory/domain/leaf/service/LeafService.java
server/src/main/java/com/growstory/global/auth/handler/OAuth2AccountSuccessHandler.java
server/src/main/resources/templates/authCode.html
server/src/main/resources/templates/password.html
server/src/test/java/com/growstory/domain/account/controller/AccountControllerTest.java

[BE] ♻️ Refactor : Account, Email, Leaf 관련 리팩토링
[BE] ♻️ Refactor : Account, Email, Leaf 관련 리팩토링
Account, Email, Leaf 관련 리팩토링
---
Close #1

[BE] ♻️ Refactor : Account, Email, Leaf 관련 리팩토링

---

server/src/test/java/com/growstory/domain/account/controller/AccountControllerTest.java

[BE] 🧪 Test : Account Controller 테스트
[BE] 🧪 Test : Account Controller 테스트
[BE] 🧪 Test : Account Controller 테스트
---
Close #1

[BE] 🧪 Test : Account Controller 테스트

---

server/src/main/java/com/growstory/domain/board/controller/BoardController.java
server/src/main/java/com/growstory/domain/board/service/BoardService.java
server/src/main/java/com/growstory/domain/hashTag/repository/HashTagRepository.java
server/src/main/java/com/growstory/domain/hashTag/service/HashTagService.java
server/src/main/java/com/growstory/domain/images/repository/BoardImageRepository.java
server/src/main/java/com/growstory/domain/images/service/BoardImageService.java
server/src/test/java/com/growstory/domain/comment/controller/CommentControllerTest.java

게시판 수정 시 이미지, 해시태그 테이블에 반영되지 않는 버그 해결
원인) 
image - 메서드 매개변수 잘못 기입
hashtag - 찾아온 hashtag를 clear() 해서 db에 반영이 안됨.
해결) 
HashTagRepository.deleteAll() 메서드 이용
키워드로 전체 게시판 조회
---
Close #87

[BE] 🐛 게시판 수정(이미지, 해시태그)

---

server/src/main/java/com/growstory/global/auth/handler/OAuth2AccountSuccessHandler.java
server/src/main/resources/application.yml
server/src/test/java/com/growstory/domain/account/controller/AccountControllerTest.java
server/src/test/java/com/growstory/domain/account/service/AccountServiceTest.java

[BE] 🧪 Test : 도형 - Account Controller 테스트, 도경 - Board, Hashtag 리팩토링, 승태 - PlantObj 테스트
[BE] 🧪 Test : 도형 - Account Controller 테스트, 도경 - Board, Hashtag 리팩토링, 승태 - PlantObj 테스트
[BE] 🧪 Test : 도형 - Account Controller 테스트, 도경 - Board, Hashtag 리팩토링, 승태 - PlantObj 테스트
---
Close #1

[BE] 🧪 Test : 도형 - Account Controller 테스트, 도경 - Board, Hashtag 리팩토링, 승태 - PlantObj 테스트

---

client/package-lock.json
client/src/api/board.ts
client/src/app/board/layout.tsx
client/src/app/board/page.tsx
client/src/app/post/[id]/page.tsx
client/src/components/board/BoardBanner.tsx
client/src/components/board/BoardSearchInput.tsx
client/src/components/board/PostCard.tsx
client/src/components/board/PostList.tsx
client/src/components/board/RankBoard.tsx
client/src/components/common/PostCountInfo.tsx
client/src/components/post/Comment.tsx
client/src/hooks/useBoardInfinityQuery.ts
client/src/styles/globals.css

* board 페이지의 비동기 요청을 구현하고 반응형 디자인을 구현했습니다.
* board 전체 조회 무한 스크롤을 통해 구현.
* board 페이지 및 구성 컴포넌트 반응형 디자인 구현.
* 랭킹 부분을 어떻게 처리할지 고민해봐야 할것 같습니다. (한 주 동안의 좋아요 수?)
---
Close #150

[FE] ✨ board 페이지 비동기 요청 구현 및 스타일링

---

server/src/main/java/com/growstory/domain/account/service/AccountService.java
server/src/main/java/com/growstory/domain/plant_object/controller/PlantObjController.java
server/src/test/java/com/growstory/domain/plant_object/controller/PlantObjectControllerTest.java
server/src/test/java/com/growstory/domain/plant_object/service/PlantObjServiceTest.java
server/src/test/java/com/growstory/domain/stubdata/Stub.java

[BE] 🧪 Test : PlantObjController API 테스트
- 정원 CRUD 슬라이스  테스트 구현
---
Close #160

[BE] 🧪 Test : PlantObjController API 테스트

---

client/src/app/garden/[id]/page.tsx
client/src/components/common/Header.tsx
client/src/components/common/Logo.tsx
client/src/components/garden/EditModeInfo.tsx
client/src/components/garden/GardenMap.tsx
client/src/components/garden/GardenSidebar.tsx
client/src/components/garden/MapController.tsx
client/src/components/garden/PlantCard.tsx
client/src/hooks/useGardenMap.ts
client/src/hooks/useMouseDrag.ts
client/src/hooks/usePlantCard.ts

* Garden 페이지의 추가 기능을 구현합니다.
* 작업 내용
---
Close #212

[FE] ✨ Garden 페이지 추가 기능 구현

---

client/src/app/page.tsx
client/src/app/post/add/page.tsx
client/src/app/post/edit/[id]/page.tsx
client/src/components/common/Intro.tsx
client/src/components/common/Logo.tsx
client/src/components/common/Modal.tsx
client/src/components/garden/PurchaseInfoModal.tsx
client/src/components/garden/PurchaseModal.tsx

* 기존 페이지, 모달 컴포넌트 스타일링을 수정합니다.
* 작업 내용

[FE] 💄 기존 페이지, 모달 컴포넌트 스타일링 수정

---

client/src/app/leaf/[userId]/[leafId]/page.tsx
client/src/app/leafs/[id]/page.tsx
client/src/components/common/Modal.tsx
client/src/components/common/ShareButton.tsx

* leaf, leafs 공유하기의 반응형 디자인 구현했습니다.
* leaf. leafs 공유하기 반응형 디자인 구현

[FE] ✨ 공유하기 (leaf, leafs) 구현

---

server/src/test/java/com/growstory/domain/leaf/service/LeafServiceTest.java

[BE] ♻️ Refactor : Leaf 리팩토링
[BE] ♻️ Refactor : Leaf 리팩토링
[BE] ♻️ Refactor : Leaf 리팩토링
---
Close #1

[BE] ♻️ Refactor : Leaf 리팩토링

---

client/src/components/common/Header.tsx
client/src/styles/globals.css

* 이미지 흐림 방지와 관련하여 전역 스타일을 추가합니다.
* 작업 내용

[FE] 🔧 이미지 흐림 방지 관련 전역 스타일 추가

---

client/src/components/history/HistoryBoard.tsx
client/src/components/history/HistoryComment.tsx
client/src/components/history/HistoryLikes.tsx
client/src/components/history/UserInfo.tsx

- [] FEAT: 새로운 기능 구현
* History 페이지 게시글 이미지 이슈 해결했습니다! 한빈님 감사해요 😆

[FE] 🐛 Fix: 게시글 이미지 이슈 해결

---

client/src/hooks/usePlantCard.ts

* Garden 페이지 포인트 관련 이슈를 해결합니다.
* 작업 내용

[FE] 🐛 Garden 페이지 포인트 관련 이슈 해결

---

client/src/components/board/RankBoard.tsx

* Board 페이지 반응형 이슈를 해결했습니다.
* 작업 내용

[FE] 🐛 Board 페이지 반응형 이슈 해결

---

client/src/components/board/RankBoard.tsx
client/src/hooks/usePlantCard.ts

* 배포를 위해 main 브랜치로 병합합니다.
* 작업 내용

[FE] 🚀 배포를 위한 브랜치 병합

---

client/src/components/history/HistoryBoard.tsx
client/src/components/history/HistoryBox.tsx
client/src/components/history/HistoryComment.tsx
client/src/components/history/HistoryLikes.tsx

* Dropdown 스타일 수정 했습니다
* 게시글 유무 안내문 스타일 수정했습니다

[FE] 💄 History Style 수정

---

server/src/main/java/com/growstory/domain/board/service/BoardService.java
server/src/main/java/com/growstory/domain/leaf/controller/LeafController.java
server/src/main/java/com/growstory/domain/leaf/service/LeafService.java
server/src/main/resources/application-prod.yml
server/src/test/java/com/growstory/domain/leaf/service/LeafServiceTest.java

[BE] ♻️ Refactor : Leaf, Point 리팩토링
[BE] ♻️ Refactor : Leaf, Point 리팩토링
---
Close #1

[BE] ♻️ Refactor : Leaf, Point 리팩토링

---

client/src/components/board/RankBoard.tsx

* board rank의 글자 색을 수정 했습니다.
* board rank의 글자 색을 수정 했습니다.

[FE] 💄 board rank 글자 색 수정

---

client/src/components/board/RankBoard.tsx
client/src/hooks/useBoardInfinityQuery.ts

* 랭크 기능의 bug를 수정했습니다. 
* 랭크 기능의 bug 수정

[FE] 🐛 board 랭크 기능 버그 fix

---

client/src/components/common/Footer.tsx
client/src/components/common/FooterLink.tsx
client/src/components/common/Preview.tsx
client/src/components/profile/ChangeNicknameModal.tsx
client/src/components/profile/ChangePasswordModal.tsx
client/src/components/signin/SigninForm.tsx

* 회원 정보 수정 관련 모달의 디자인을 수정했습니다.
* 닉네임에 + 가 나오는 오류를 수정했습니다.
* footer의 링크를 새 탭으로 열리게 수정했습니다.
* 회원 정보 수정 관련 모달의 디자인을 수정
* 닉네임에 + 가 나오는 오류를 수정했
* footer의 링크를 새 탭으로 열리게 수정

[FE] 🐛 3차 테스트 후 발생한 오류 수정

---

README.md

* README.md 파일 내용을 업데이트합니다.
* 작업 내용
- README.md 파일 내용 업데이트

[FE/BE] 📝 README.md 파일 내용 업데이트

---

.github/workflows/server.yml
server/src/main/java/com/growstory/domain/board/repository/BoardRepository.java
server/src/main/java/com/growstory/domain/board/service/BoardService.java
server/src/main/java/com/growstory/domain/rank/board_likes/entity/BoardLikesRank.java
server/src/main/java/com/growstory/domain/rank/board_likes/history/entity/BoardLikesRankHistory.java
server/src/main/java/com/growstory/domain/rank/board_likes/service/BoardLikesRankService.java
server/src/main/java/com/growstory/domain/rank/entity/Rank.java
server/src/main/java/com/growstory/global/auth/config/SecurityCorsConfig.java
server/src/main/java/com/growstory/global/auth/handler/OAuth2AccountSuccessHandler.java
server/src/main/java/com/growstory/global/auth/utils/AuthUserUtils.java
server/src/main/java/com/growstory/global/aws/service/S3Uploader.java
server/src/test/java/com/growstory/domain/board/service/BoardServiceTest.java

- 게시글 상세 페이지 게스트 허용
---
Close #87

♻️ Refactor : 게시글 상세 페이지 게스트 허용

---

client/src/app/post/[id]/page.tsx
client/src/app/post/add/page.tsx
client/src/components/board/RankBoard.tsx
client/src/components/common/PostCountInfo.tsx

* 게시글 상세 페이지 비로그인 접근 방지
* 게시글 상세 비로그인 접근 방지
#278

[FE] ♻️ 게시글 상세 페이지 비로그인 뷰 관련 수정

---

client/src/app/post/add/page.tsx
client/src/components/common/PostCountInfo.tsx
client/src/components/signup/AuthEmailModal.tsx

* alert 관련 이슈를 해결합니다.
* 이메일 인증 모달에 안내 메시지를 추가합니다.
* 작업 내용

[FE] 🐛 alert 관련 이슈 해결

---

client/src/api/board.ts
client/src/api/garden.ts
client/src/api/history.ts
client/src/api/leaf.ts
client/src/api/post.ts
client/src/api/profile.ts
client/src/app/post/add/page.tsx
client/src/app/profile/page.tsx
client/src/components/common/HeaderNav.tsx
client/src/components/common/PostCountInfo.tsx
client/src/components/history/HistoryBox.tsx
client/src/components/history/SuccessedModal.tsx
client/src/components/profile/ProfileBox.tsx
client/src/components/signup/AuthEmailModal.tsx
client/src/constants/values.ts
client/src/stores/userStore.ts

* 관리자 ID인 경우 조건부 렌더링을 추가했습니다.
* alert 관련 이슈를 해결했습니다.
* sessionStorage 관련 로직을 변경했습니다.
* 작업 내용

[FE] ✨ 관리자 ID인 경우 조건부 렌더링 추가

---

client/src/components/board/PostCard.tsx
client/src/components/common/ShareButton.tsx
client/src/components/main/ServiceInfo.tsx
client/src/constants/values.ts

* 이미지 컴포넌트 관련 이슈를 해결합니다.
* 공유 버튼 이슈를 해결합니다.
* 작업 내용

[FE] 🐛 이미지 컴포넌트 관련 이슈, 공유 버튼 이슈 해결

---

server/src/main/java/com/growstory/domain/plant_object/service/PlantObjService.java
server/src/main/java/com/growstory/domain/point/controller/PointController.java
server/src/main/java/com/growstory/domain/point/service/PointService.java
server/src/main/java/com/growstory/global/email/service/EmailService.java
server/src/main/resources/application-prod.yml

이벤트 포인트 지급 기능 구현
---
Close #237 

✨ Feat : 이벤트 포인트 지급 기능 구현

---

client/src/api/axios.ts
client/src/api/history.ts
client/src/api/profile.ts
client/src/components/history/ConfirmModal.tsx
client/src/components/history/HistoryBoard.tsx
client/src/components/history/HistoryComment.tsx
client/src/components/history/HistoryLikes.tsx
client/src/components/history/ResignModal.tsx
client/src/components/history/UserInfo.tsx
client/src/components/profile/ImageForm.tsx
client/src/components/profile/NicknameForm.tsx
client/src/components/profile/PasswordForm.tsx
client/src/components/signin/SigninForm.tsx
client/src/components/signup/SignupForm.tsx
client/src/hooks/mutation/useAuthEmailMutation.ts
client/src/hooks/mutation/useChangeImageMutation.ts
client/src/hooks/mutation/useChangeNicknameMutation.ts
client/src/hooks/mutation/useChangePasswordMutation.ts
client/src/hooks/mutation/useDeleteUserMutation.ts
client/src/hooks/mutation/useResignCheckMutation.ts
client/src/hooks/mutation/useSigninMutation.ts
client/src/hooks/mutation/useSignupMutation.ts
client/src/hooks/query/useHistoryBoardQuery.ts
client/src/hooks/query/useHistoryCommentQuery.ts
client/src/hooks/query/useHistoryLikesQuery.ts
client/src/hooks/query/useUserInfoQuery.ts
client/src/hooks/useFindPassword.ts
client/src/stores/userStore.ts

*  axios 컴포넌트 구현 및 react query hooks 네이밍 리팩토링을 작업했습니다
* useFindPassword 훅은 query랑 mutation을 분리하게 되면 query가 작동을 제대로 안하는 이슈가 생겨서 일단은 분리하지 않았습니다
후에 다시 시도해보겠습니다!
---
Close #309

[FE] ✨ axios 컴포넌트 구현 및 react query hooks 네이밍 리팩토링

---

server/src/main/java/com/growstory/domain/account/entity/Account.java
server/src/main/java/com/growstory/domain/account/service/AccountService.java
server/src/main/java/com/growstory/global/auth/config/PasswordEncoderConfig.java
server/src/main/java/com/growstory/global/auth/config/SecurityConfiguration.java
server/src/main/java/com/growstory/global/auth/filter/JwtVerificationFilter.java
server/src/main/java/com/growstory/global/auth/handler/AccountAuthenticationSuccessHandler.java
server/src/main/java/com/growstory/global/auth/handler/OAuth2AccountSuccessHandler.java

[BE] ✨	feat : 출석 체크 기능
[BE] ✨	feat : 출석 체크 기능
---
Close #1

[BE] ✨	feat : 출석 체크 기능

---

server/src/main/java/com/growstory/domain/account/constants/Status.java
server/src/main/java/com/growstory/domain/account/controller/AccountController.java
server/src/main/java/com/growstory/domain/account/entity/Account.java
server/src/main/java/com/growstory/domain/account/service/AccountService.java
server/src/main/java/com/growstory/domain/alarm/constants/AlarmType.java
server/src/main/java/com/growstory/domain/alarm/controller/AlarmController.java
server/src/main/java/com/growstory/domain/alarm/dto/AlarmDto.java
server/src/main/java/com/growstory/domain/alarm/entity/Alarm.java
server/src/main/java/com/growstory/domain/alarm/repository/AlarmRepository.java
server/src/main/java/com/growstory/domain/alarm/service/AlarmService.java
server/src/main/java/com/growstory/domain/board/service/BoardService.java
server/src/main/java/com/growstory/domain/journal/service/JournalService.java
server/src/main/java/com/growstory/domain/leaf/controller/LeafController.java
server/src/main/java/com/growstory/domain/leaf/service/LeafService.java
server/src/main/java/com/growstory/global/auth/config/SecurityCorsConfig.java
server/src/main/java/com/growstory/global/email/controller/EmailController.java
server/src/main/java/com/growstory/global/exception/ExceptionCode.java
server/src/main/java/com/growstory/global/sse/controller/SseController.java
server/src/main/java/com/growstory/global/sse/repository/SseEmitterRepository.java
server/src/main/java/com/growstory/global/sse/service/SseService.java

[BE] ✨ feat : 알림 기능 구현
---
Close #1

[BE] ✨ feat : 알림 기능 구현

---

server/src/main/java/com/growstory/domain/account/service/AccountService.java
server/src/main/java/com/growstory/domain/guest/service/GuestService.java
server/src/main/java/com/growstory/global/email/service/EmailService.java

*  ♻️Refactoring : Guest Mode - Guest Email, DisplayName 저장 방식 변경
♻️Refactoring : Guest Mode - Guest Email, DisplayName UUID -> 8자리 난수
---
Close #323 

 ♻️Refactoring : Guest Mode - Guest Email, DisplayName 저장 방식 변경

---

server/src/main/java/com/growstory/domain/account/entity/Account.java
server/src/main/java/com/growstory/domain/account/service/AccountService.java

*  신고 기능 추가로 인해 추가된 Account(reportNum) 필드, 게스트 계정 생성 시 값 추가
*  신고 기능 추가로 인해 추가된 Account(reportNum) 필드, 게스트 계정 생성 시 값 추가
---
Close #315

 ♻️Refactoring : Guest 계정 생성 시 누락된 reportNum 필드  데이터 추가

---

server/src/main/java/com/growstory/domain/account/service/AccountService.java
server/src/main/java/com/growstory/global/email/dto/EmailDto.java
server/src/main/java/com/growstory/global/email/service/EmailService.java

[BE] 🐛 Fix : account 생성, email 비밀번호 찾기 수정
---
Close #1

[BE] 🐛 Fix : account 생성, email 비밀번호 찾기 수정

---

server/src/main/java/com/growstory/domain/account/controller/AccountController.java
server/src/main/java/com/growstory/domain/account/service/AccountService.java
server/src/main/java/com/growstory/domain/guest/service/GuestService.java
server/src/main/java/com/growstory/domain/plant_object/entity/PlantObj.java

* 게스트 회원 가입 시 토큰 추가
* Response: body - email 제거 / header - Location, AccessToken, Refresh 추가 
---
Close #315 

♻️ Refactor : 게스트 회원 가입 토큰 추가

---

server/src/main/java/com/growstory/domain/qnachat/chatmessage/constant/ChatMessageConstants.java
server/src/main/java/com/growstory/domain/qnachat/chatmessage/controller/ChatMessageController.java
server/src/main/java/com/growstory/domain/qnachat/chatmessage/controller/ChatMessageStompController.java
server/src/main/java/com/growstory/domain/qnachat/chatmessage/service/ChatMessageService.java
server/src/main/java/com/growstory/domain/qnachat/chatmessage/service/ChatMessageServiceImpl.java
server/src/main/java/com/growstory/domain/qnachat/chatroom/controller/ChatRoomController.java
server/src/main/java/com/growstory/domain/qnachat/chatroom/dto/ChatRoomResponseDto.java
server/src/main/java/com/growstory/domain/qnachat/chatroom/dto/CreateQnaChatRequest.java
server/src/main/java/com/growstory/domain/qnachat/chatroom/dto/SimpChatRoomRequestDto.java
server/src/main/java/com/growstory/domain/qnachat/chatroom/entity/ChatRoom.java
server/src/main/java/com/growstory/domain/qnachat/chatroom/service/ChatRoomService.java
server/src/main/java/com/growstory/domain/qnachat/chatroom/service/ChatRoomServiceImpl.java
server/src/main/java/com/growstory/global/email/controller/EmailController.java
server/src/main/java/com/growstory/global/email/dto/EmailDto.java
server/src/main/java/com/growstory/global/email/service/EmailService.java
server/src/main/resources/templates/qnaResponse.html

[BE] ✨ 실시간 채팅 구현
- 답변 완료 이메일 api 추가
- 채팅방 목록 조회 페이지네이션
- 답변 여부 필드 추가 및 갱신 api 추가
- 채팅방 목록 조회 페이지네이션으로 변경
- 답장 여부 필드(isAnswered) 추가
- createdAt, latestTime 날짜만 나올 수 있게
- 채팅방 생성시 qnaTitle 추가
- 입장 메시지 변경
- 답변 여부 필드 추가
- 답변 여부 갱신 api 추가
- 답변 이메일 전송 api 추가
---
Close #319

[BE] ✨ 실시간 채팅 구현

---

client/src/app/history/[id]/page.tsx
client/src/app/profile/page.tsx
client/src/app/signin/page.tsx
client/src/app/signup/page.tsx
client/src/components/history/ConfirmModal.tsx
client/src/components/history/FailureModal.tsx
client/src/components/history/ResignModal.tsx
client/src/components/history/SuccessedModal.tsx
client/src/components/profile/ChangeProfileModal.tsx
client/src/components/signin/FailureModal.tsx
client/src/components/signin/FindPasswordModal.tsx
client/src/components/signin/MembershipCheckModal.tsx
client/src/components/signin/SuccessedModal.tsx
client/src/components/signup/AuthEmailModal.tsx
client/src/components/signup/FailureModal.tsx
client/src/components/signup/MembershipCheckModal.tsx
client/src/constants/values.ts
client/src/hooks/useModal.ts

* signin, signup, history, profile 에서 사용하는 모달 컴포넌트에서 발생한 에러를 해결했습니다.
* admin의 userId를 52에서 101로 수정했습니다
---
Close #350

[FE] 🐛 모달 컴포넌트 이슈 해결

---

.github/workflows/server.yml
server/src/main/java/com/growstory/domain/account/service/AccountService.java
server/src/main/java/com/growstory/domain/guest/service/GuestService.java
server/src/main/java/com/growstory/domain/guestbook/dto/GuestBookResponseDto.java
server/src/main/java/com/growstory/domain/guestbook/service/GuestBookService.java

* 게스트 계정 생성 로직 변경, 방명록 조회 로직 변경
1. Guest 계정 생성 로직 수정(식물카드/오브젝트 연결, 1L -> plantObjId)
2. 방명록 조회 시 최신순 정렬, 작성자아이디(AuthorId)
---
Close #315 

♻️ Refactor: 게스트 계정 생성 로직 변경, 방명록 조회 로직 변경

---

.github/workflows/server.yml
server/src/main/java/com/growstory/domain/account/service/AccountService.java
server/src/main/java/com/growstory/domain/guest/service/GuestService.java

* Guest 기능 로직 수정
guest 계정 생성 기능 로직 수정
---
Close #315 

♻️ Refactor: Guest 계정 생성 로직 수정

---

server/src/main/java/com/growstory/domain/guestbook/service/GuestBookService.java

* 방명록 조회 최신순으로 정렬
* 방명록 조회 최신순으로 정렬

♻️ Refactor: 방명록 조회 최신순 정렬

---

client/src/components/common/index.ts
client/src/components/history/HistoryBoard.tsx
client/src/components/history/HistoryComment.tsx
client/src/components/history/HistoryLikes.tsx

* 프론트 배포 이슈를 해결합니다.
* 작업 내용
- 프론트 배포 이슈 해결

[FE] 🐛 프론트 배포 이슈 해결

---

client/src/app/garden/[id]/page.tsx
client/src/app/history/[id]/page.tsx
client/src/app/page.tsx
client/src/app/profile/page.tsx

* 누락된 페이지에 알림 버튼을 추가합니다.
* 작업 내용

[FE] ✨ 모든 페이지에 알림 버튼 추가

---

client/next.config.js

* 웹소켓 콘솔 관련 이슈를 해결합니다.
* 작업 내용

[FE] 🐛 웹소켓 콘솔 관련 이슈 해결

---

server/src/test/java/com/growstory/domain/alarm/controller/AlarmControllerTest.java
server/src/test/java/com/growstory/domain/likes/controller/LikeControllerTest.java
server/src/test/java/com/growstory/domain/point/controller/PointControllerTest.java

[BE] ✨ Feat : Alarm, Like, Point Controller 테스트 코드 작성

[BE] ✨ Feat : Alarm, Like, Point Controller 테스트 코드 작성

---

server/src/main/java/com/growstory/domain/account/entity/Account.java
server/src/test/java/com/growstory/domain/account/service/AccountServiceTest.java
server/src/test/java/com/growstory/domain/point/controller/PointControllerTest.java

[BE] 🧪 Test : Point Controller, Account Service 테스트 코드 작성
- [] FEAT: 새로운 기능 구현
---
Close #1

[BE] 🧪 Test  : Point Controller, Account Service 테스트 코드 작성

---

client/src/app/garden/[id]/page.tsx

[FE] 🐛 배포 관련 이슈 해결
